services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes      
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - kafka-networks
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_READONLY=false
      - KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE=true
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - kafka-networks
  order-service:
    build: ../order-service
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - mongo
    networks:
      - kafka-networks

  notification-service:
    build: ../notification-service
    ports:
      - "5002:5002"
    depends_on:
      - kafka
      - mongo
    networks:
      - kafka-networks

  payment-service:
    build: ../payment-service
    ports:
      - "5001:5001"
    depends_on:
      - kafka
      - mongo
    networks:
      - kafka-networks
  mongo:
    image: mongo
    container_name: mongo
    ports:
    - "27017:27017"
    networks:
    - kafka-networks
networks:
  kafka-networks:
    driver: bridge
